-- data.sql
-- 사용자 데이터
INSERT INTO users (username) VALUES ('변의진');
INSERT INTO users (username) VALUES ('오원택');
INSERT INTO users (username) VALUES ('백진욱');
INSERT INTO users (username) VALUES ('신제원');
INSERT INTO users (username) VALUES ('수강생1');
INSERT INTO users (username) VALUES ('수강생2');
INSERT INTO users (username) VALUES ('수강생3');
INSERT INTO users (username) VALUES ('수강생4');
INSERT INTO users (username) VALUES ('수강생5');
INSERT INTO users (username) VALUES ('수강생6');
INSERT INTO users (username) VALUES ('수강생7');
INSERT INTO users (username) VALUES ('수강생8');
INSERT INTO users (username) VALUES ('수강생9');
INSERT INTO users (username) VALUES ('수강생10');
INSERT INTO users (username) VALUES ('수강생11');
INSERT INTO users (username) VALUES ('수강생12');
INSERT INTO users (username) VALUES ('수강생13');
INSERT INTO users (username) VALUES ('수강생14');
INSERT INTO users (username) VALUES ('수강생15');
INSERT INTO users (username) VALUES ('수강생16');
INSERT INTO users (username) VALUES ('수강생17');
INSERT INTO users (username) VALUES ('수강생18');
INSERT INTO users (username) VALUES ('수강생19');
INSERT INTO users (username) VALUES ('수강생20');
INSERT INTO users (username) VALUES ('수강생21');
INSERT INTO users (username) VALUES ('수강생22');
INSERT INTO users (username) VALUES ('수강생23');
INSERT INTO users (username) VALUES ('수강생24');
INSERT INTO users (username) VALUES ('수강생25');
INSERT INTO users (username) VALUES ('수강생26');
INSERT INTO users (username) VALUES ('수강생27');
INSERT INTO users (username) VALUES ('수강생28');
INSERT INTO users (username) VALUES ('수강생29');
INSERT INTO users (username) VALUES ('수강생30');
INSERT INTO users (username) VALUES ('수강생31');
INSERT INTO users (username) VALUES ('수강생32');
INSERT INTO users (username) VALUES ('수강생33');
INSERT INTO users (username) VALUES ('수강생34');
INSERT INTO users (username) VALUES ('수강생35');
INSERT INTO users (username) VALUES ('수강생36');

-- 특강 데이터
INSERT INTO lecture (title, description, lecturer, capacity, lecture_date) VALUES ('1주차 TDD 기초강의', 'TDD에 대해 기초강의를 합니다', '허재', 30, '2024-10-01');
INSERT INTO lecture (title, description, lecturer, capacity, lecture_date) VALUES ('1주차 TDD 기초강의', 'TDD에 대해 기초강의를 합니다', '허재', 30, '2024-10-01');
INSERT INTO lecture (title, description, lecturer, capacity, lecture_date) VALUES ('2주차 clean code', 'clean code 에 대해 강의합니다', '허재', 30, '2024-10-02');
INSERT INTO lecture (title, description, lecturer, capacity, lecture_date) VALUES ('3주차 강의', 'TDD에 대해 기초강의를 합니다', '허재', 30, '2024-10-03');
INSERT INTO lecture (title, description, lecturer, capacity, lecture_date) VALUES ('4주차 강의', 'TDD에 대해 기초강의를 합니다', '허재', 30, '2024-10-04');
INSERT INTO lecture (title, description, lecturer, capacity, lecture_date) VALUES ('5주차 강의', 'TDD에 대해 기초강의를 합니다', '허재', 30, '2024-10-05');
INSERT INTO lecture (title, description, lecturer, capacity, lecture_date) VALUES ('6주차 강의', 'TDD에 대해 기초강의를 합니다', '허재', 30, '2024-10-06');
